quarkus.http.port=8081
quarkus.smallrye-graphql-client.inventory.url=http://localhost:8083/graphql


##Testing
quarkus.http.test-port=8181
#quarkus.test.profile.tags=staying
#quarkus.test.profile.tags=nothing uncomment this line to test with other profile and not run staging test

#Security configuration
quarkus.oidc.application-type=service
%prod.quarkus.oidc.auth-server-url=http://localhost:7777/realms/car-rental
%prod.quarkus.oidc.client-id=reservation-service
%prod.quarkus.oidc.token-state-manager.split-tokens=true

#DATABASE
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=pass
#reactive way
%prod.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/reservation
#traditional way
#%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/reservation

#DROP AND CREATE DATABASE
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

#RABBITMQ
mp.messaging-incoming-invoices-rabbitmq.queue.name=invoices
mp.messaging-incoming-invoices-rabbitmq.exchange.name=invoices

#Testing
#%test.mp.messaging-outgoing-invoices-rabbitmq.queue.name=invoices
#%test.mp.messaging-outgoing-invoices-rabbitmq.exchange.name=invoices
%test.mp.messaging.incoming.invoices-rabbitmq.queue.name=invoices
%test.mp.messaging.incoming.invoices-rabbitmq.exchange.name=invoices